services:

    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/credit_card_management_system
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=root
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PORT=6379
        ports:
            - "8081:8080"
        depends_on:
            - postgres
        restart: on-failure

    postgres:
        image: postgres
        container_name: postgres
        restart: on-failure
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=credit_card_management_system
        volumes:
            - "./data:/var/lib/postgresql/data"
